### PR TITLE
Atomicity updates for Thread Sanitizer warnings

### LINKED ISSUE #227: Thread Sanitizer: Swift access race in Segment.CountBasedFlushPolicy.count.modify : Swift.Int at 0x11a75f4c0
**Describe the bug**

When running our app with the Xcode Thread Sanitizer enabled, we sometimes see this runtime warning: `Swift access race in Segment.CountBasedFlushPolicy.count.modify : Swift.Int at 0x11a75f4c0`

It's flagged within the `CountBasedFlushPolicy` class at this line of code:

```
   public func updateState(event: RawEvent) {
        count += 1      <-----
    }
```

**To Reproduce**

1. Edit the current main app target (iOS) scheme
2. For the Run (Debug) section, select Diagnostics, enable "Thread Sanitizer" check box
3. Run app

**Expected behavior**
No runtime warnings

**Platform (please complete the following information):**
 - Library Version in use: 1.4.5 (But I don't think this issue is new to this version)
 - Platform being tested: iOS 16.4 on simulator
 - Integrations in use: None except custom proxy

### PR DESCRIPTION
**Pull request by bsneed**
- Refactor the Atomic property wrapper.
- Fix lack of atomicity in CountBasedFlushPolicy
- Added documentation and references in code re atomicity changes.
- Fixes #227

### CODE REVIEW

**Review by didiergarcia — APPROVED** [review]

File: Sources/Segment/Utilities/Atomic.swift [hunk 1]
```diff
@@ -7,29 +7,26 @@
...
+//
+// Also see thread here: https://github.com/apple/swift-evolution/pull/1387
+
 @propertyWrapper
-public struct Atomic<T> {
-    var value: T
-    private let lock = NSLock()
+public class Atomic<T> {
+    private var value: T
+    private let queue = DispatchQueue(label: "com.segment.atomic.\(UUID().uuidString)")
```
Comment (didiergarcia) [inline Sources/Segment/Utilities/Atomic.swift:22]: Nice 👍
